### ISSUE TITLE
Error when using FlatList:  Failed to execute 'importScripts' on 'WorkerGlobalScope

### ISSUE THREAD

**Issue by bnovf** [bnovf/react-native-github-graphql-app#3]
I get this error when I import flatList into my react-native app. When I have FlatList as an import:
```import { Text, FlatList  } from 'react-native'```

from the expo simulator screen

![img_20171029_083459](https://user-images.githubusercontent.com/12845124/32140988-ac34f342-bc84-11e7-9711-3834ebe6f1f2.jpg)

```
abi21_0_0.com.facebook.react.common .JavascriptException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://1 92.1 68.0.1 3:19001/ node_modules/react-native-scripts/ 

build/bin/crna-entry.bundle? platform=android&dev=true&strict=false&min 

ify=false&hot=false&assetPlugin=expo/tools/ hashAssetFiles' failed to load. 

Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http:// 192.168.0.13:19001/node_modules/reactnative-scripts/build/bin/crna-entry.bundle? platform=android&dev=true&strict=false&min ify=faIse&hot=false&assetPlugin=expoltoolsl hashAssetFiles' failed to load. 

loadApplicationScript WebsocketJavaScriptExecutor.java:173 

run NativeRunnable.java
```
Something like this facebook/react-native#13558  and this https://github.com/facebook/react-native/issues/6035

**Comment by bnovf** [comment]
https://github.com/facebook/react-native/issues/13558

**Comment by bnovf** [comment]
https://stackoverflow.com/questions/46997358/error-when-rendering-flatlist-with-default-props-failed-to-execute-importscript

**Comment by bnovf** [comment]
fixed by changing the renderItem prop
```        <FlatList
          data={responseData}
          renderItem={({item}) => <Text >{item.node.nameWithOwner}</Text>}
        />
```
https://stackoverflow.com/questions/46997358/error-when-rendering-flatlist-with-default-props-failed-to-execute-importscript

**Comment by bnovf** [comment]
With his error, you are almost sure it's an issue with your `export` or `import` statements...  e.g check any file you might have exported or default exported twice...

**Comment by q3e** [comment]
https://github.com/react-community/create-react-native-app/issues/401

**Comment by PeterHassaballah** [comment]
Try restarting your metro bundler .
